[project]
name = "apspace-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.14.2",
    "google-adk==1.11.0",
    "mcp[cli]>=1.25.0",
    "requests>=2.32.5",
]
